spring:
  application:
    name: ai-community-backend
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  web:
    resources:
      # 禁用默认静态资源处理，避免与API路径冲突
      add-mappings: false
server:
  port: 8200
  servlet:
      context-path: /api

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zheng.aicommunitybackend.domain.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    root: info
    com.zheng.aicommunitybackend: debug

# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.zheng.aicommunitybackend.controller
# knife4j配置
knife4j:
  enable: true
  setting:
    language: zh_cn

# 新闻爬虫配置
spider:
  enabled: true
  user-agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
  timeout: 10000
  finance-news:
    enabled: true
    wall-street-cn-url: "https://wallstreetcn.com/news/global"
    caixin-url: "https://www.caixin.com/finance/"

# 布隆过滤器配置
bloom-filter:
  # 预计插入的元素数量（7天约21000条数据，设置50000容量提供安全余量）
  expected-insertions: 50000
  # 可接受的误判率
  false-positive-probability: 0.01
  # 数据保留天数（只保留最近7天的数据用于去重）
  data-retention-days: 7
  # 是否启用自动重建（每天凌晨2点执行）
  auto-rebuild-enabled: true
  # 监控配置
  monitoring:
    # 是否启用监控
    enabled: true
    # 检查间隔（分钟，7天周期需要更频繁监控）
    check-interval-minutes: 15
    # 邮件告警配置
    email-alert-enabled: false
    # 钉钉告警配置
    dingtalk-alert-enabled: false
    dingtalk-webhook-url: ""
    # 企业微信告警配置
    wechat-alert-enabled: false
    wechat-webhook-url: ""
    # Prometheus指标配置
    prometheus-enabled: false


