spring:
  application:
    name: ai-community-backend
  profiles:
    active: dev
server:
  port: 8200
  servlet:
      context-path: /api

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zheng.aicommunitybackend.domain.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    root: info
    com.zheng.aicommunitybackend: debug

# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.zheng.aicommunitybackend.controller
# knife4j???????????????
knife4j:
  enable: true
  setting:
    language: zh_cn